{ pkgs, inputs, ... }:

{
    environment.systemPackages = with pkgs; [
        arduino-cli
        arduino-ide
        bat
        brightnessctl
        btop
        cmake
        kdePackages.dolphin
        direnv
        dmenu
        docker-compose
        fastfetch
        firefox
        freecad-wayland
        fzf
        gcc
        gh
        ghostty
        grimblast
        hyprcursor
        hypridle
        hyprpicker
        hyprsunset
        rose-pine-hyprcursor
        killall
        kitty
        lazygit
        libnotify
        matugen
        neovim
        networkmanager
        networkmanagerapplet
        nh
        orca-slicer
        pavucontrol
        power-profiles-daemon
        pyenv
        qmk
        inputs.quickshell.packages.${pkgs.system}.default
        ripgrep
        rofi-wayland
        spotify
        starship
        swayimg
        swaynotificationcenter
        swww
        tlp
        tmux
        tree
        unzip
        waybar
        wf-recorder
        wl-clipboard
        wlogout
        yazi
        zellij
        zoxide
    ];

    services.flatpak.packages = [
        "app.zen_browser.zen"
    ];
}
