{ pkgs, inputs, ... }:

{
    environment.systemPackages = with pkgs; [
        arduino-cli
        arduino-ide
        bat
        brightnessctl
        btop
        cifs-utils
        coreutils
        kdePackages.dolphin
        direnv
        dmenu
        docker-compose
        emacs
        fastfetch
        firefox
        freecad-wayland
        fzf
        gh
        ghostty
        grimblast
        home-manager
        hyprcursor
        hypridle
        hyprlock
        hyprpanel
        hyprpicker
        hyprsunset
        rose-pine-hyprcursor
        inxi
        kanata
        kicad
        killall
        kitty
        lazygit
        libnotify
        localsend
        matugen
        neovim
        nh
        obsidian
        # orca-slicer
        pavucontrol
        power-profiles-daemon
        psmisc
        pyenv
        protonmail-desktop
        qmk
        rofi-wayland
        rsync
        spotify
        starship
        swayimg
        swaynotificationcenter
        swww
        tlp
        tmux
        tree
        unzip
        vesktop
        vlc
        waybar
        wf-recorder
        wl-clipboard
        wlogout
        yazi
        zellij
        zoxide
    ];
}
